ARG NODE_VERSION=20.14.0
FROM node:${NODE_VERSION}-alpine as base

WORKDIR /frontend
COPY package*.json .
COPY . .
RUN npm install && npm run build

ENV NODE_ENV=development
ENV HOST 0.0.0.0
EXPOSE 3000

CMD [ "npm", "run", "dev" ]

